# docker-compose.yml
version: '3.8'
services:
  backend:
    image: your_image_name
    ports:
      - "5000:5000"
    environment:
      PORT: "custom_port"
      SESSION_SECRET: "your_secure_session_secret"
      OPENAI_APIKEY: "your OPENAI_APIKEY"
      DB_NAME: "your_database_name"
      DB_USER: "your_database_username"
      DB_PASS: "your_database_password"
      DB_HOST: "your_database_host"
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:3306/${DB_NAME}"
